bookyourdoctor/Controllers/Clinic_requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class Clinic_requestController : Controller
    {
        public static string ideee = patientsController.idee;
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: Clinic_request
        public ActionResult Index()
        {
            return View(db.Clinic_request.ToList());
        }

        // GET: Clinic_request/Create
        public ActionResult Create1(int idee)
        {
            
            Clinic_request p = new Clinic_request();
            doctor_scedule doctor_shedule = db.doctor_scedule.Find(idee);
            p.doctor_id = doctor_shedule.doctor_id;
            p.clinic_day = doctor_shedule.Clinic_day;
            p.patient_name = ideee;
            p.clinic_start_time = doctor_shedule.clinic_start_time;
            p.clinic_end_time = doctor_shedule.clinic_end_time;
            db.Clinic_request.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }

        public ActionResult Index1()
        {
            return View();
        }



        // GET: Clinic_request/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // GET: Clinic_request/Create
        public ActionResult Create()
        {
            return View();

           
        }

        // POST: Clinic_request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,id,clinic_day,doctor_id")] Clinic_request clinic_request)
        {
            if (ModelState.IsValid)
            {
                db.Clinic_request.Add(clinic_request);
                try
                {
                    db.SaveChanges();
                }
                catch( Exception e)
                {
                    Console.WriteLine(e);

                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clinic_request);
        }

        // GET: Clinic_request/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // POST: Clinic_request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,id,clinic_day,doctor_id")] Clinic_request clinic_request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clinic_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic_request);
        }

        // GET: Clinic_request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // POST: Clinic_request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            db.Clinic_request.Remove(clinic_request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/Hospital_requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class Hospital_requestController : Controller
    {
        public static string ideee = patientsController.idee;
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: Hospital_request
        public ActionResult Index()
        {
            return View(db.Hospital_request.ToList());
        }

        // GET: Hospital_request/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        public ActionResult Create1(int idee)
        {

            Hospital_request p = new Hospital_request();
            doctor_scedule doctor_shedule = db.doctor_scedule.Find(idee);
            p.doctor_id = doctor_shedule.doctor_id;
            p.Hospital_day = doctor_shedule.hospial_day;
            p.patient_name = ideee;
            p.Hospital_start_time = doctor_shedule.hospital_start_time;
            p.hospital_end_time = doctor_shedule.hospital_end_time;
            
            db.Hospital_request.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index1","Clinic_request");
        }
        

        // GET: Hospital_request/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospital_request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hospital_start_time,hospital_end_time,patient_name,Hospital_day,id,doctor_id")] Hospital_request hospital_request)
        {
            if (ModelState.IsValid)
            {
                db.Hospital_request.Add(hospital_request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospital_request);
        }

        // GET: Hospital_request/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        // POST: Hospital_request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hospital_start_time,hospital_end_time,patient_name,Hospital_day,id,doctor_id")] Hospital_request hospital_request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital_request);
        }

        // GET: Hospital_request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            if (hospital_request == null)
            {
                return HttpNotFound();
            }
            return View(hospital_request);
        }

        // POST: Hospital_request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hospital_request hospital_request = db.Hospital_request.Find(id);
            db.Hospital_request.Remove(hospital_request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class doctorsController : Controller
    {
        public FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: doctors
        public ActionResult Index()
        {
            return View(db.doctors.ToList());
        }

        // GET: doctors/Details/5
        public ActionResult Details(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
        public ActionResult viewDetails(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(doctor p)
        {
            using (FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3())
            {
                var usr = db.doctors.SingleOrDefault(u => u.doctor_id == p.doctor_id);
                if (usr != null)
                {
                    if (usr.password.ToString() == p.password.ToString())
                    {
                        Session["doctor_id"] = usr.doctor_id.ToString();
                        return RedirectToAction("DoctorWelcome1","doctor_scedule", new { ide = usr.doctor_id.ToString()});

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password is wrong");
                }
            }
            return View(p);

        }

       

        // GET: doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }


        public ActionResult ViewShedule(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
        
        






        // GET: doctors/Edit/5
        public ActionResult Edit(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: doctors/Delete/5
        public ActionResult Delete(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ide)
        {
            doctor doctor = db.doctors.Find(ide);
            db.doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Views/doctors/Details.cshtml
@model bookyourdoctor.doctor
@{
    ViewBag.Title = "Details";
    doctor ABC = new doctor();
    ABC.name = Model.name;
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 500px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:100% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DOCTOR DETAILS</b></center>
                <dl class="dl-horizontal" style="padding-left:80px">
                    <dt>
                        @Html.DisplayNameFor(model => model.name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.date_of_birth)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.date_of_birth)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.adress)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.adress)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.phone)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.phone)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MBBS_Code)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.MBBS_Code)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.email)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.password)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.password)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.confirm_password)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.confirm_password)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.clinic_name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.clinic_name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.hospital_address)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.hospital_address)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.hospital_name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.hospital_name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.clinic_address)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.clinic_address)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.city)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.city)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.specialization)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.specialization)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.practising_years)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.practising_years)
                    </dd>
                </dl>
                <p>@Html.ActionLink("View Shedule", "ViewShedule", "doctors", new { ide = Model.doctor_id }, null)</p> @*, new { ide = Model.doctor_id, idee=Model.clinic_name, ideee=Model.hospital_name, ad }, null)*@
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/doctors/Index.cshtml
@model IEnumerable<bookyourdoctor.doctor>
@{
    ViewBag.Title = "Index";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DOCTORS</b></center>
                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.phone)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.email)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.clinic_name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.hospital_name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.specialization)
                        </th>

                        <th></th>
                    </tr>
                    @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.phone)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.clinic_name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.hospital_name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.specialization)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", "doctors", new { ide = item.doctor_id }, null) |
                    @Html.ActionLink("View Details", "viewDetails", "doctors", new { ide = item.doctor_id }, null) |
                    @Html.ActionLink("Delete", "Delete", "doctors", new { ide = item.doctor_id }, null)
                </td>
            </tr>
}
                </table>
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/doctors/Login.cshtml
@model bookyourdoctor.doctor
@{
    ViewBag.Title = "DoctorLogin";
}
<head>
    <style type="text/css">


        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 500px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:100% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DOCTOR LOGIN</b></center>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form>
                        <div class="form-group">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-4"><label>Doctor ID :</label></div>
                            @Html.EditorFor(model => model.doctor_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-4">
                                <label>Password :</label>
                            </div>
                            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="login" class="btn btn-default" style="margin-left:130px;width:90px;background-color: #2992de;color:white" />
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/doctors/ViewShedule.cshtml
@model bookyourdoctor.doctor
@{
    ViewBag.Title = "ViewShedule";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DOCTOR SCHEDULE</b></center>
                @{
        doctor_scedule dg = new doctor_scedule();
        IEnumerable<doctor_scedule> lst = dg.doctorsspec(Model.doctor_id);
                }

                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

            <p>CLINIC NAME:@Html.DisplayFor(modelItem => Model.clinic_name)</p><br>
            <p>CLINIC ADDRESS:@Html.DisplayFor(modelItem => Model.clinic_address)</p><br>



            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <th style="font-family:Arial;font-size:24px">DAY</th>
                        <th style="font-family:Arial;font-size:24px">CLINIC OPEN TIME</th>
                        <th style="font-family:Arial;font-size:24px">CLINIC CLOSE TIME</th>
                        <th style="font-family:Arial;font-size:24px">APPOITMENT</th>
                    </tr>
                    @foreach (var item in lst.ToList())
        {
            <tr>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.Clinic_day)</td>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_start_time)</td>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.clinic_end_time)</td>
                <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Take Appoitment", "Create1", "Clinic_request", new { idee = item.id }, null)</td>
            </tr>

}
                </tbody>
            </table>

            <p>HOSPITAL NAME:@Html.DisplayFor(modelItem => Model.hospital_name)</p><br>
            <p>HOSPITAL ADDRESS:@Html.DisplayFor(modelItem => Model.hospital_address)</p><br>



            <table class="table table-bordered table-condensed">
                <tbody>
                    <tr>
                        <th style="font-family:Arial;font-size:24px">DAY</th>
                        <th style="font-family:Arial;font-size:24px">HOSPITAL OPEN TIME</th>
                        <th style="font-family:Arial;font-size:24px">HOSPITAL CLOSE TIME</th>
                        <th style="font-family:Arial;font-size:24px">APPOITMENT</th>
                    </tr>
                    @foreach (var item in lst.ToList())
        {
            <tr>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospial_day)</td>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_start_time)</td>
                <td style="font-family:Arial;font-size:24px">@Html.DisplayFor(modelItem => item.hospital_end_time)</td>
                <td style="font-family:Arial;font-size:24px">@Html.ActionLink("Take Appoitment", "Create1", "Hospital_request", new { idee = item.id }, null)</td>
            </tr>

}
                </tbody>
            </table>
}
            </div>
        </div>
    </div>
</body>