bookyourdoctor/Controllers/Clinic_requestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class Clinic_requestController : Controller
    {
        public static string ideee = patientsController.idee;
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: Clinic_request
        public ActionResult Index()
        {
            return View(db.Clinic_request.ToList());
        }

        // GET: Clinic_request/Create
        public ActionResult Create1(int idee)
        {
            
            Clinic_request p = new Clinic_request();
            doctor_scedule doctor_shedule = db.doctor_scedule.Find(idee);
            p.doctor_id = doctor_shedule.doctor_id;
            p.clinic_day = doctor_shedule.Clinic_day;
            p.patient_name = ideee;
            p.clinic_start_time = doctor_shedule.clinic_start_time;
            p.clinic_end_time = doctor_shedule.clinic_end_time;
            db.Clinic_request.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }

        public ActionResult Index1()
        {
            return View();
        }



        // GET: Clinic_request/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // GET: Clinic_request/Create
        public ActionResult Create()
        {
            return View();

           
        }

        // POST: Clinic_request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,id,clinic_day,doctor_id")] Clinic_request clinic_request)
        {
            if (ModelState.IsValid)
            {
                db.Clinic_request.Add(clinic_request);
                try
                {
                    db.SaveChanges();
                }
                catch( Exception e)
                {
                    Console.WriteLine(e);

                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clinic_request);
        }

        // GET: Clinic_request/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // POST: Clinic_request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,id,clinic_day,doctor_id")] Clinic_request clinic_request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clinic_request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic_request);
        }

        // GET: Clinic_request/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            if (clinic_request == null)
            {
                return HttpNotFound();
            }
            return View(clinic_request);
        }

        // POST: Clinic_request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clinic_request clinic_request = db.Clinic_request.Find(id);
            db.Clinic_request.Remove(clinic_request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/clinic_viewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class clinic_viewController : Controller
    {
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: clinic_view
        public ActionResult Index()
        {
            return View(db.clinic_view.ToList());
        }

        public ActionResult Create1(int idee)
        {
            clinic_view p = new clinic_view();
            Clinic_request clinic_request = db.Clinic_request.Find(idee);
            
            p.Clinic_day = clinic_request.clinic_day;
            p.patient_name = clinic_request.patient_name;
            p.clinic_start_time = clinic_request.clinic_start_time;
            p.clinic_end_time = clinic_request.clinic_end_time;
            
            db.clinic_view.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }

        public ActionResult Index1()
        {
            return View();
        }



        // GET: clinic_view/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // GET: clinic_view/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: clinic_view/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,Clinic_day,id")] clinic_view clinic_view)
        {
            if (ModelState.IsValid)
            {
                db.clinic_view.Add(clinic_view);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clinic_view);
        }

        // GET: clinic_view/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // POST: clinic_view/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,Clinic_day,id")] clinic_view clinic_view)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clinic_view).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic_view);
        }

        // GET: clinic_view/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // POST: clinic_view/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            clinic_view clinic_view = db.clinic_view.Find(id);
            db.clinic_view.Remove(clinic_view);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Views/clinic_view/Create.cshtml
@model bookyourdoctor.clinic_view
@{
    ViewBag.Title = "Create";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CLINIC VIEW</b></center>
                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
              
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.clinic_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.clinic_start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.clinic_start_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.clinic_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.clinic_end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.clinic_end_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Clinic_day, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Clinic_day, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Clinic_day, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
}
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/clinic_view/Delete.cshtml
@model bookyourdoctor.clinic_view
@{
    ViewBag.Title = "Delete";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CLINIC VIEW</b></center>
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.patient_name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Clinic_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Clinic_day)
                        </dd>
                    </dl>
                    @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
}
                </div>
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/clinic_view/Details.cshtml
@model bookyourdoctor.clinic_view
@{
    ViewBag.Title = "Details";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CLINIC DETAILS</b></center>
                <div>
                    
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.patient_name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Clinic_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Clinic_day)
                        </dd>
                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/clinic_view/Edit.cshtml
@model bookyourdoctor.clinic_view
@{
    ViewBag.Title = "Edit";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CLINIC VIEW</b></center>
                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
              
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.clinic_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.clinic_start_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.clinic_start_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.clinic_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.clinic_end_time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.clinic_end_time, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.patient_name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.patient_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.patient_name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Clinic_day, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Clinic_day, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Clinic_day, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.id)
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
}
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/clinic_view/Index.cshtml
@model IEnumerable<bookyourdoctor.clinic_view>
@{
    ViewBag.Title = "Index";
}
model bookyourdoctor.doctor
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            height: 1700px;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id=" form" style=" background-color: #acbdca;height:0% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CLINIC SCHEDULE</b></center>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.clinic_start_time)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.clinic_end_time)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.patient_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Clinic_day)
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.clinic_start_time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.clinic_end_time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.patient_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clinic_day)
                </td>
            </tr>
}
                </table>
            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/clinic_view/Index1.cshtml
@{
    ViewBag.Title = "Index1";
}

<h2>Thanks for your response patient will be informed by the status of his appoitment</h2>

@Html.ActionLink("Back to list", "Index","Clinic_request")