bookyourdoctor/Controllers/clinic_viewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class clinic_viewController : Controller
    {
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: clinic_view
        public ActionResult Index()
        {
            return View(db.clinic_view.ToList());
        }

        public ActionResult Create1(int idee)
        {
            clinic_view p = new clinic_view();
            Clinic_request clinic_request = db.Clinic_request.Find(idee);
            
            p.Clinic_day = clinic_request.clinic_day;
            p.patient_name = clinic_request.patient_name;
            p.clinic_start_time = clinic_request.clinic_start_time;
            p.clinic_end_time = clinic_request.clinic_end_time;
            
            db.clinic_view.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }

        public ActionResult Index1()
        {
            return View();
        }



        // GET: clinic_view/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // GET: clinic_view/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: clinic_view/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,Clinic_day,id")] clinic_view clinic_view)
        {
            if (ModelState.IsValid)
            {
                db.clinic_view.Add(clinic_view);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clinic_view);
        }

        // GET: clinic_view/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // POST: clinic_view/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clinic_start_time,clinic_end_time,patient_name,Clinic_day,id")] clinic_view clinic_view)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clinic_view).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic_view);
        }

        // GET: clinic_view/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clinic_view clinic_view = db.clinic_view.Find(id);
            if (clinic_view == null)
            {
                return HttpNotFound();
            }
            return View(clinic_view);
        }

        // POST: clinic_view/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            clinic_view clinic_view = db.clinic_view.Find(id);
            db.clinic_view.Remove(clinic_view);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/doctor_sceduleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class doctor_sceduleController : Controller
    {
        private FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: doctor_scedule
        public ActionResult Index()
        {
            return View(db.doctor_scedule.ToList());
        }

        // GET: doctor_scedule/Details/5
        public ActionResult Details(int ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor_scedule doctor_scedule = db.doctor_scedule.Find(ide);
            if (doctor_scedule == null)
            {
                return HttpNotFound();
            }
            return View(doctor_scedule);
        }

        // GET: doctor_scedule/Create
        public ActionResult Create(String ide)
        {
            doctor_scedule p = new doctor_scedule();
            p.doctor_id = ide;
            return View(p);
        }

        // POST: doctor_scedule/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "clinic_start_time,hospital_start_time,clinic_end_time,hospital_end_time,is_avalible,Clinic_day,hospial_day,doctor_id")] doctor_scedule doctor_scedule)
        {
            
            if (ModelState.IsValid)
            {
                db.doctor_scedule.Add(doctor_scedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor_scedule);
        }

        public ActionResult ViewShedule(string ide)
        {
            doctor dp = new doctor();
            dp.doctor_id = ide.Trim();
            Session["doctor_id"] = ide.Trim();
            return View(dp);
        }

        public ActionResult Viewrequests()
        {
            return View();
        }




        public ActionResult DoctorWelcome1(string ide)
        {
            doctor dp = new doctor();
            dp.doctor_id = ide.Trim();
            Session["doctor_id"] = ide.Trim();
            return View(dp);
        }

        // GET: doctor_scedule/Edit/5
        public ActionResult Edit(int ide)
        {

            
            
            
            doctor_scedule doctor_scedule =db.doctor_scedule.Find(ide);
            if (doctor_scedule == null)
            {
                return HttpNotFound();
            }
            return View(doctor_scedule);
        }

        // POST: doctor_scedule/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "clinic_start_time,hospital_start_time,clinic_end_time,hospital_end_time,Clinic_day,hospial_day,doctor_id")] doctor_scedule doctor_scedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor_scedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor_scedule);
        }

        // GET: doctor_scedule/Delete/5
        public ActionResult Delete(int ide)
        {
            
            doctor_scedule doctor_scedule = db.doctor_scedule.Find(ide);
            if (doctor_scedule == null)
            {
                return HttpNotFound();
            }
            return View(doctor_scedule);
        }

        // POST: doctor_scedule/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ide)
        {
            
            doctor_scedule doctor_scedule = db.doctor_scedule.Find(ide.Trim());
            db.doctor_scedule.Remove(doctor_scedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Controllers/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;

namespace bookyourdoctor.Controllers
{
    public class doctorsController : Controller
    {
        public FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3();

        // GET: doctors
        public ActionResult Index()
        {
            return View(db.doctors.ToList());
        }

        // GET: doctors/Details/5
        public ActionResult Details(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
        public ActionResult viewDetails(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(doctor p)
        {
            using (FINALSCRIPTTEntities3 db = new FINALSCRIPTTEntities3())
            {
                var usr = db.doctors.SingleOrDefault(u => u.doctor_id == p.doctor_id);
                if (usr != null)
                {
                    if (usr.password.ToString() == p.password.ToString())
                    {
                        Session["doctor_id"] = usr.doctor_id.ToString();
                        return RedirectToAction("DoctorWelcome1","doctor_scedule", new { ide = usr.doctor_id.ToString()});

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password is wrong");
                }
            }
            return View(p);

        }

       

        // GET: doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }


        public ActionResult ViewShedule(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }
        
        






        // GET: doctors/Edit/5
        public ActionResult Edit(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "doctor_id,name,date_of_birth,adress,phone,MBBS_Code,email,password,confirm_password,clinic_name,hospital_address,hospital_name,clinic_address,city,specialization,practising_years")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: doctors/Delete/5
        public ActionResult Delete(string ide)
        {
            if (ide == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doctors.Find(ide);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string ide)
        {
            doctor doctor = db.doctors.Find(ide);
            db.doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

bookyourdoctor/Views/doctor_scedule/Create.cshtml
@model bookyourdoctor.doctor_scedule
@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            background-size: 100% 100%;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id=" form" style=" background-color: #acbdca;height:100% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">CREATE SCHEDULE</b></center>
                @using (Html.BeginForm())
    {
            @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.clinic_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.clinic_start_time, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.clinic_start_time, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.clinic_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.clinic_end_time, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.clinic_end_time, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.hospital_start_time, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.hospital_start_time, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.hospital_start_time, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.hospital_end_time, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.hospital_end_time, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.hospital_end_time, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Clinic_day, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(x => x.Clinic_day, doctor_scedule.GetDay())
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.hospial_day, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(x => x.hospial_day, doctor_scedule.GetDay())
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.doctor_id, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.doctor_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.doctor_id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
}
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>


            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/doctor_scedule/Delete.cshtml
@model bookyourdoctor.doctor_scedule
@{
    ViewBag.Title = "Delete";
}
<head>
    <style type="text/css">

        body {
            background-image: url(../images/qqq.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            background-size: 100% 100%;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id=" form" style=" background-color: #acbdca;height:100% 100%;opacity:0.9;

    ">
                <center style="text-align:center ;
	padding-top: 60px;padding-bottom:60px"><b class="registration">DELETE SCHEDULE</b></center>
                <h2>Delete</h2>
                <h3>Are you sure you want to delete this?</h3>
                <div>

                    <dl class="dl-horizontal" style="padding-left:80px">
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.hospital_start_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.hospital_start_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.clinic_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.clinic_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.hospital_end_time)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.hospital_end_time)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.is_avalible)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.is_avalible)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Clinic_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Clinic_day)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.hospial_day)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.hospial_day)
                        </dd>
                    </dl>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</body>

bookyourdoctor/Views/doctor_scedule/DoctorWelcome1.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "DoctorWelcome1";
}


<body style="background-image:url(../images/qqq.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  min-height:400px;
  ">
    <style>


        .head {
            font-family: Arial;
            font-size: 44px;
            margin-top: 50px;
            color: white;
        }

        .img-circle {
            width: 300px;
            height: 300px;
            border-radius: 50%;
            background: white;
            margin-top: 60px;
            margin-bottom: 30px;
            background-color: darkgrey;
            border-style: solid;
            border-color: darkgrey;
            opacity: 0.9;
        }

            .img-circle:hover {
                border-style: solid;
                border-color: white;
                background-color: darkturquoise;
            }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 450px;
        }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 950px;
        }
    </style>
    <h1 class=" head" style="text-align:center"> <u> <b> DOCTORS HANDLER</b> </u> </h1>
    <div class="row ">
        @Html.HiddenFor(model => model.doctor_id)
        <div class="img-circle col-md-2.5" style="margin-left:20px">
            <h2 class="text" style=" color:white; margin-top:115px;text-align:center "><b>@Html.ActionLink("CREATE SHEDULE", "Create", "doctor_scedule", new { ide = Model.doctor_id }, new { })</b></h2>
        </div>


        <div class="img-circle col-md-2.5" style="margin-left:50px">
            <h2 class="text" style="color:white;margin-top:115px;text-align:center"><b>@Html.ActionLink("VIEW REQUESTS", "Viewrequests", "doctor_scedule", new { ide = Model.doctor_id }, new { })</b></h2>
        </div>


        <div class="img-circle col-md-2.5" style="margin-left:50px">
            <h2 class="text" style="color:white;margin-top:115px;text-align:center"><b>@Html.ActionLink("VIEW SHEDULE", "ViewShedule", "doctor_scedule", new { ide = Model.doctor_id }, new { })</b></h2>
        </div>
        <div class="img-circle col-md-2.5" style="margin-left:50px">
            <h2 class="text" style="color:white;margin-top:115px;text-align:center"><b>@Html.ActionLink("EDIT PROFILE", "Edit", "doctors", new { ide = Model.doctor_id }, new { })</b></h2>
        </div>
        
        
    </div>


</body>

bookyourdoctor/Views/doctor_scedule/ViewShedule.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "View Shedule";
}

<h2>DoctorWelcome1</h2>

<body style="background-image:url(../images/qqq.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  min-height:400px;
  ">
    <style>


        .head {
            font-family: Arial;
            font-size: 44px;
            margin-top: 50px;
            color: white;
        }

        .img-circle {
            width: 300px;
            height: 300px;
            border-radius: 50%;
            background: white;
            margin-top: 60px;
            margin-bottom: 30px;
            background-color: darkgrey;
            border-style: solid;
            border-color: darkgrey;
            opacity: 0.9;
        }

            .img-circle:hover {
                border-style: solid;
                border-color: white;
                background-color: darkturquoise;
            }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 450px;
        }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 950px;
        }
    </style>
    <h1 class=" head" style="text-align:center"> <u> <b> DOCTORS HANDLER</b> </u> </h1>
    <div class="row ">
        @Html.HiddenFor(model => model.doctor_id)
        <div class="img-circle col-md-2.5" style="margin-left:20px">
            <h2 class="text" style=" color:white; margin-top:115px;text-align:center "><b>@Html.ActionLink("VIEW HOSPITAL SHEDULE", "Index", "hospital_view")</b></h2>
        </div>


        <div class="img-circle col-md-2.5" style="margin-left:50px">
            <h2 class="text" style="color:white;margin-top:115px;text-align:center"><b>@Html.ActionLink("VIEW CLINIC SHEDULE", "Index", "clinic_view")</b></h2>
        </div>


        
    </div>


</body>

bookyourdoctor/Views/doctor_scedule/Viewrequests.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "Viewrequests";
}

<h2>Viewrequests</h2>

<body style="background-image:url(../images/qqq.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  min-height:400px;
  ">
    <style>


        .head {
            font-family: Arial;
            font-size: 44px;
            margin-top: 50px;
            color: white;
        }

        .img-circle {
            width: 300px;
            height: 300px;
            border-radius: 50%;
            background: white;
            margin-top: 60px;
            margin-bottom: 30px;
            background-color: darkgrey;
            border-style: solid;
            border-color: darkgrey;
            opacity: 0.9;
        }

            .img-circle:hover {
                border-style: solid;
                border-color: white;
                background-color: darkturquoise;
            }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 450px;
        }

        #circle2 {
            width: 300px;
            height: 350px;
            border-radius: 50%;
            background: white;
            position: relative;
            margin-top: 100px;
            margin-left: 950px;
        }
    </style>
    <h1 class=" head" style="text-align:center"> <u> <b> DOCTORS HANDLER</b> </u> </h1>
    <div class="row ">
        @Html.HiddenFor(model => model.doctor_id)
        <div class="img-circle col-md-2.5" style="margin-left:20px">
            <h2 class="text" style=" color:white; margin-top:115px;text-align:center "><b>@Html.ActionLink("VIEW HOSPITAL REQUESTS", "Index", "Hospital_request")</b></h2>
        </div>


        <div class="img-circle col-md-2.5" style="margin-left:50px">
            <h2 class="text" style="color:white;margin-top:115px;text-align:center"><b>@Html.ActionLink("VIEW CLINIC REQUESTS", "Index", "Clinic_request")</b></h2>
        </div>



    </div>


</body>